"""Agent-level execution harness (PH2.0).

Run ONE Functional Agent in isolation against a serialized AgentContext fixture,
validate pre/post-conditions, emit a context diff and a mini trace. This is an
ADDITIONAL execution path — it does not modify the Functional Agent Contract,
AgentContext/AgentResult schemas, or the Orchestrator.

Usage:
    python -m functional_agents.run_agent --agent planner --fixture fixtures/planner_start.json
    python -m functional_agents.run_agent --agent evidence --fixture fixtures/evidence_start.json --no-llm
    python -m functional_agents.run_agent --agent recommendation \
        --fixture fixtures/recommendation_start.json --output updated_context.json --trace mini.trace.json

Fixture format: a JSON object of AgentContext fields (the durable ones). Unknown
keys are ignored; missing fields fall back to AgentContext defaults. See
fixtures/README.md.
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
import time
from pathlib import Path
from typing import Any, Callable

from .context import AgentContext
from .context_snapshot import (
    HarnessError,
    CONTEXT_FIELDS,
    context_to_jsonable,
    load_context,
    context_diff,
)

LOGGER = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Precondition / postcondition specs
# ---------------------------------------------------------------------------

def _has_question_or_target(ctx: AgentContext) -> bool:
    return bool((ctx.question or "").strip()) or bool(ctx.get_reasoning_targets())


def _plan_present(ctx: AgentContext) -> bool:
    return bool(ctx.plan) and bool(ctx.plan.get("subquestions") or ctx.plan.get("investigation_areas"))


def _evidence_present(ctx: AgentContext) -> bool:
    return bool(ctx.evidence_notes) and bool(ctx.evidence_notes[0].get("evidence_items") is not None)


def _hypotheses_present(ctx: AgentContext) -> bool:
    return bool(ctx.hypotheses)


def _prepare_report(ctx: AgentContext) -> None:
    """ReportAgent needs a ResearchMemo object in trace scratch (not JSON-able).

    Rebuild it from a fixture-provided `trace._memo` dict, or synthesize a minimal
    memo from the question + evidence so the report agent can run in isolation.
    """
    from research_agent.schemas import ResearchMemo, EvidenceItem

    memo = ctx.trace.get("_memo")
    if isinstance(memo, ResearchMemo):
        pass
    elif isinstance(memo, dict):
        ctx.trace["_memo"] = ResearchMemo(**memo)
    else:
        ev_note = ctx.evidence_notes[0] if ctx.evidence_notes else {}
        facts = [e.get("claim", "") for e in ev_note.get("evidence_items", [])][:5]
        ctx.trace["_memo"] = ResearchMemo(
            title=f"Report: {ctx.question}",
            question=ctx.question or "(harness)",
            executive_summary="Synthetic memo generated by the agent harness.",
            confirmed_facts=[f for f in facts if f],
        )
    ctx.trace.setdefault("_documents", [])


# Registry: name -> builder + pre/post conditions + declared products.
# Each condition is (description, predicate(ctx)->bool).
AGENT_REGISTRY: dict[str, dict[str, Any]] = {
    "planner": {
        "import": ("planner_agent", "PlannerAgent"),
        "build": lambda cls, client, profiles, cfg: cls(client=client, domain_profiles=profiles),
        "pre": [("question or reasoning target present", _has_question_or_target)],
        "post": [("plan.research_type produced", lambda c: bool(c.plan.get("research_type")))],
        "produces": ["plan", "domain_plans"],
    },
    "evidence": {
        "import": ("evidence_agent", "EvidenceAgent"),
        "build": lambda cls, client, profiles, cfg: cls(
            sources_dir=cfg["sources"], client=client, domain_profiles=profiles,
            retriever=cfg.get("retriever"), use_reranker=cfg.get("rerank", False),
        ),
        "pre": [("plan present (subquestions/investigation_areas)", _plan_present)],
        "post": [("evidence_notes produced", lambda c: bool(c.evidence_notes))],
        "produces": ["evidence_notes", "domain_evidence"],
    },
    "hypothesis": {
        "import": ("hypothesis_agent", "HypothesisAgent"),
        "build": lambda cls, client, profiles, cfg: cls(client=client, domain_profiles=profiles),
        "pre": [("evidence_notes present", _evidence_present)],
        "post": [("hypotheses produced", lambda c: bool(c.hypotheses))],
        "produces": ["hypotheses", "domain_hypotheses"],
    },
    "strategic_synthesis": {
        "import": ("strategic_synthesis_agent", "StrategicSynthesisAgent"),
        "build": lambda cls, client, profiles, cfg: cls(client=client, domain_profiles=profiles),
        "pre": [("hypotheses or domain_hypotheses present",
                 lambda c: bool(c.hypotheses or c.domain_hypotheses))],
        "post": [("strategic_synthesis produced", lambda c: bool(c.strategic_synthesis))],
        "produces": ["strategic_synthesis"],
    },
    "recommendation": {
        "import": ("recommendation_agent", "RecommendationAgent"),
        "build": lambda cls, client, profiles, cfg: cls(client=client, domain_profiles=profiles),
        "pre": [("hypotheses present", _hypotheses_present)],
        "post": [("recommendations produced", lambda c: bool(c.recommendations))],
        "produces": ["recommendations", "recommendation_portfolio"],
    },
    "report": {
        "import": ("report_agent", "ReportAgent"),
        "build": lambda cls, client, profiles, cfg: cls(out_path=cfg["out"], domain_profile=None),
        "prepare": _prepare_report,
        "pre": [("question present", lambda c: bool((c.question or "").strip()))],
        "post": [("report artifact produced", lambda c: bool(c.artifacts.get("report_path")))],
        "produces": ["report", "artifacts"],
    },
}


# ---------------------------------------------------------------------------
# Execution
# ---------------------------------------------------------------------------

def _load_profiles(ctx: AgentContext) -> list[Any]:
    from research_agent.profile import load_profile
    profiles: list[Any] = []
    for name in ctx.profiles:
        try:
            profiles.append(load_profile(name))
        except Exception:
            pass
    return profiles


def _build_retriever(knowledge_store: Path | None):
    """Best-effort Knowledge Layer retriever (lexical works without an API key)."""
    if not knowledge_store or not knowledge_store.exists():
        return None
    try:
        from knowledge.store import KnowledgeStore
        from knowledge.retriever import EvidenceRetriever
        from knowledge.embeddings import get_provider
        from knowledge.health import check_store_health
        ks = KnowledgeStore(knowledge_store)
        if not check_store_health(ks).runtime_ready:
            LOGGER.warning("[harness] knowledge store not runtime-ready — legacy retrieval")
            return None
        try:
            provider = get_provider()
        except Exception:
            provider = None
        return EvidenceRetriever(ks, provider=provider)
    except Exception as exc:
        LOGGER.warning("[harness] retriever init failed (%s) — legacy retrieval", exc)
        return None


def _check_conditions(conditions: list[tuple[str, Callable]], ctx: AgentContext, kind: str) -> list[str]:
    failures = []
    for desc, pred in conditions:
        try:
            ok = bool(pred(ctx))
        except Exception as exc:
            ok = False
            desc = f"{desc} (raised {type(exc).__name__})"
        if not ok:
            failures.append(desc)
    if failures:
        joined = "; ".join(failures)
        raise HarnessError(f"{kind} failed for agent: {joined}")
    return [desc for desc, _ in conditions]


def run_agent(
    agent_name: str,
    fixture_path: str | Path,
    *,
    no_llm: bool = False,
    model: str | None = None,
    sources: str | Path = "fixtures/sources",
    knowledge_store: str | Path | None = None,
    out_path: str | Path = "outputs/harness_report.md",
) -> dict[str, Any]:
    """Execute one agent in isolation; return {context, diff, mini_trace}."""
    if agent_name not in AGENT_REGISTRY:
        raise HarnessError(
            f"Unknown agent '{agent_name}'. Known: {', '.join(sorted(AGENT_REGISTRY))}"
        )
    spec = AGENT_REGISTRY[agent_name]

    ctx = load_context(fixture_path)
    before = context_to_jsonable(ctx)

    # Client (mock when --no-llm or no API key).
    from .cli import _build_client
    import os
    use_mock = no_llm or not os.getenv("ANTHROPIC_API_KEY")
    client = _build_client(mock=use_mock, model=model)
    ctx.trace["_client"] = client
    llm_before = len(getattr(client, "call_traces", []))

    profiles = _load_profiles(ctx)

    # Knowledge store auto-detect (mirrors functional CLI).
    ks_path = Path(knowledge_store) if knowledge_store else None
    if ks_path is None and Path("knowledge_store").exists():
        ks_path = Path("knowledge_store")
    cfg = {
        "sources": Path(sources),
        "out": Path(out_path),
        "retriever": _build_retriever(ks_path) if agent_name == "evidence" else None,
        "rerank": False,
    }

    # Build the agent.
    mod_name, cls_name = spec["import"]
    module = __import__(f"functional_agents.{mod_name}", fromlist=[cls_name])
    agent_cls = getattr(module, cls_name)
    agent = spec["build"](agent_cls, client, profiles, cfg)

    # Optional per-agent preparation (e.g. rebuild non-JSON scratch objects).
    if spec.get("prepare"):
        spec["prepare"](ctx)

    # Preconditions (pre-run harness usage failures raise HarnessError).
    pre_checked = _check_conditions(spec["pre"], ctx, "Precondition")

    # Execute. Execution-time failures (e.g. LLM boundary rejection) are captured
    # into the mini trace as a distinct error rather than crashing the harness,
    # so boundary stages/failures are always reported.
    status = "error"
    post_checked: list[str] = []
    exec_error: str | None = None
    t0 = time.monotonic()
    try:
        result = agent.run(ctx)
        ctx = result.context
        status = result.status
        post_checked = _check_conditions(spec["post"], ctx, "Postcondition")
    except HarnessError as exc:      # postcondition failure
        exec_error = str(exc)
    except Exception as exc:          # agent / boundary execution failure
        exec_error = f"{type(exc).__name__}: {exc}"
    elapsed_ms = round((time.monotonic() - t0) * 1000, 1)

    after = context_to_jsonable(ctx)
    diff = context_diff(before, after)

    llm_calls = len(getattr(client, "call_traces", [])) - llm_before
    norm = ctx.trace.get("_llm_normalization")
    # PH2.1 — surface any LLM-boundary diagnostics (keys ending in _boundary).
    boundary = {
        k: v for k, v in ctx.trace.items()
        if isinstance(k, str) and k.endswith("_boundary")
    }
    # PH3.3 — surface any applied prompt-slice diagnostics (keys ending in
    # _prompt_slice), additively — absent entirely for agents PH3.3 didn't touch.
    prompt_slice = {
        k: v for k, v in ctx.trace.items()
        if isinstance(k, str) and k.endswith("_prompt_slice")
    }
    warnings = [
        h.get("summary", "") for h in ctx.agent_history
        if h.get("status") in ("warning", "error")
    ]

    mini_trace = {
        "agent": agent_name,
        "agent_class": cls_name,
        "status": status,
        "error": exec_error,
        "execution_time_ms": elapsed_ms,
        "llm_call_count": llm_calls,
        "llm_mode": "mock" if use_mock else "live",
        "normalization": norm,
        "boundary": boundary,
        "prompt_slice": prompt_slice,
        "validation": {
            "preconditions_passed": pre_checked,
            "postconditions_passed": post_checked,
        },
        "objects_produced": diff["added"] + diff["modified"],
        "warnings": warnings,
    }

    return {"context": after, "diff": diff, "mini_trace": mini_trace}


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _print_summary(res: dict[str, Any]) -> None:
    mt = res["mini_trace"]
    d = res["diff"]
    print(f"\n=== Agent Harness — {mt['agent']} ({mt['agent_class']}) ===")
    print(f"  status         : {mt['status']}")
    if mt.get("error"):
        print(f"  error          : {mt['error']}")
    print(f"  time           : {mt['execution_time_ms']} ms")
    print(f"  llm calls      : {mt['llm_call_count']} ({mt['llm_mode']})")
    print(f"  preconditions  : {'; '.join(mt['validation']['preconditions_passed']) or '(none)'}")
    print(f"  postconditions : {'; '.join(mt['validation']['postconditions_passed']) or '(none)'}")
    for name, bd in (mt.get("boundary") or {}).items():
        stages = bd.get("stages") if isinstance(bd, dict) else None
        failed = bd.get("failed_stage") if isinstance(bd, dict) else None
        print(f"  {name:<15}: stages={stages} failed_stage={failed}")
    for name, ps in (mt.get("prompt_slice") or {}).items():
        if not isinstance(ps, dict):
            continue
        print(
            f"  {name:<15}: {ps.get('original_bytes')}→{ps.get('sliced_bytes')} bytes "
            f"({ps.get('reduction_pct')}% reduction, {ps.get('fields_excluded_count')} fields excluded)"
        )
    print("\n  Context diff:")
    print(f"    added    ({len(d['added'])}): {', '.join(d['added']) or '-'}")
    print(f"    modified ({len(d['modified'])}): {', '.join(d['modified']) or '-'}")
    print(f"    unchanged({len(d['unchanged'])})")
    if mt["warnings"]:
        print(f"\n  Warnings: {mt['warnings']}")
    print("")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m functional_agents.run_agent",
        description="Execute one Functional Agent in isolation (PH2.0).",
    )
    parser.add_argument("--agent", required=True, help=f"One of: {', '.join(sorted(AGENT_REGISTRY))}")
    parser.add_argument("--fixture", required=True, help="Path to AgentContext fixture JSON")
    parser.add_argument("--output", help="Write updated context JSON here")
    parser.add_argument("--trace", help="Write mini trace JSON here")
    parser.add_argument("--no-llm", action="store_true", help="Force deterministic mock client")
    parser.add_argument("--model", help="Anthropic model name (live mode)")
    parser.add_argument("--sources", default="fixtures/sources", help="Sources dir for evidence legacy path")
    parser.add_argument("--knowledge-store", help="Knowledge store dir (auto-detects knowledge_store/)")
    parser.add_argument("--out", default="outputs/harness_report.md", help="Report output path (report agent)")
    parser.add_argument("--log-level", default="WARNING")
    args = parser.parse_args(argv)

    logging.basicConfig(level=getattr(logging, args.log_level.upper(), logging.WARNING),
                        format="%(levelname)s %(name)s: %(message)s")

    try:
        res = run_agent(
            args.agent, args.fixture,
            no_llm=args.no_llm, model=args.model,
            sources=args.sources, knowledge_store=args.knowledge_store, out_path=args.out,
        )
    except HarnessError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    _print_summary(res)

    if args.output:
        Path(args.output).parent.mkdir(parents=True, exist_ok=True)
        Path(args.output).write_text(json.dumps(res["context"], indent=2, ensure_ascii=False), encoding="utf-8")
        print(f"Updated context → {args.output}")
    if args.trace:
        Path(args.trace).parent.mkdir(parents=True, exist_ok=True)
        Path(args.trace).write_text(json.dumps(res["mini_trace"], indent=2, ensure_ascii=False), encoding="utf-8")
        print(f"Mini trace → {args.trace}")

    # Non-zero exit on an execution/boundary failure (deterministic).
    return 0 if res["mini_trace"]["status"] != "error" else 1


if __name__ == "__main__":
    raise SystemExit(main())
