"""Strategic Engagement – top-level context object for a consulting engagement (J7.0a).

A Strategic Engagement represents the input a strategy consultant receives from a
CEO, investor, or government client.  It sits above Research Objects in the hierarchy:

    Strategic Engagement
        ↓
    Problem Framing → Decision Model
        ↓
    Research Object(s)
        ↓
    Executive Decision Report  (future milestone)

Objects are written to outputs/engagements/<engagement_id>.json.

Backward compatibility
----------------------
All existing Research Objects remain valid.  The engagement layer is additive:
Research Objects gain two optional nullable reference fields (engagement_id,
decision_model_id) but are otherwise unchanged.

When the CLI is invoked with a bare question, a minimal Engagement is created
automatically via ``from_question()``.  No behavioural change results.
"""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Literal

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Schema
# ---------------------------------------------------------------------------

EngagementType = Literal[
    "investment_decision",
    "policy_decision",
    "strategic_planning",
    "risk_assessment",
    "market_entry",
    "regulatory_response",
    "general",                 # default for question-driven / legacy runs
]

EngagementStatus = Literal["draft", "active", "complete", "archived"]


class StrategicEngagement(BaseModel):
    """Top-level engagement context (J7.0a).

    Required fields capture the intent supplied by the client.
    Optional fields provide richer context when available.
    Generated fields are populated by downstream agents.
    """

    # --- Identity ----------------------------------------------------------
    engagement_id: str
    created_at: str

    # --- Client-supplied (required) ----------------------------------------
    client: str                          # organisation or individual name
    brief: str                           # raw brief text, verbatim from client
    strategic_question: str              # distilled core decision/question
    engagement_type: EngagementType = "general"
    status: EngagementStatus = "active"

    # --- Client-supplied (optional) ----------------------------------------
    decision_deadline: str | None = None         # ISO date string or free text
    client_context: str | None = None            # industry, constraints, risk tolerance
    constraints: list[str] = Field(default_factory=list)
    stakeholders: list[str] = Field(default_factory=list)
    background_documents: list[str] = Field(default_factory=list)

    # --- Generated by downstream agents ------------------------------------
    decision_model_id: str | None = None         # populated by ProblemFramingAgent
    research_object_ids: list[str] = Field(default_factory=list)
    executive_report_id: str | None = None       # reserved for future milestone

    def to_dict(self) -> dict[str, Any]:
        return self.model_dump()


# ---------------------------------------------------------------------------
# Factory helpers
# ---------------------------------------------------------------------------

def _new_engagement_id() -> str:
    ts = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    return f"ENG-{ts}"


def create_engagement(
    *,
    client: str,
    brief: str,
    strategic_question: str,
    engagement_type: EngagementType = "general",
    decision_deadline: str | None = None,
    client_context: str | None = None,
    constraints: list[str] | None = None,
    stakeholders: list[str] | None = None,
    background_documents: list[str] | None = None,
    status: EngagementStatus = "active",
) -> StrategicEngagement:
    """Create a new StrategicEngagement with a generated ID and timestamp."""
    return StrategicEngagement(
        engagement_id=_new_engagement_id(),
        created_at=datetime.now(timezone.utc).isoformat(),
        client=client,
        brief=brief,
        strategic_question=strategic_question,
        engagement_type=engagement_type,
        decision_deadline=decision_deadline,
        client_context=client_context,
        constraints=constraints or [],
        stakeholders=stakeholders or [],
        background_documents=background_documents or [],
        status=status,
    )


def from_question(question: str, *, client: str = "internal") -> StrategicEngagement:
    """Create a minimal engagement from a bare research question.

    Used by CLI and benchmark runs for backward compatibility.  The question
    serves as both the brief and the strategic_question.  No behavioural
    change to any downstream agent.
    """
    return create_engagement(
        client=client,
        brief=question,
        strategic_question=question,
        engagement_type="general",
        status="active",
    )


# ---------------------------------------------------------------------------
# Persistence
# ---------------------------------------------------------------------------

_ENG_DIR = Path("outputs/engagements")
_LATEST_PATH = Path("outputs/latest_engagement.json")


def write_engagement(
    engagement: StrategicEngagement,
    base: Path = Path("outputs"),
) -> Path:
    """Persist the engagement to disk and update latest_engagement.json."""
    eng_dir = base / "engagements"
    eng_dir.mkdir(parents=True, exist_ok=True)
    path = eng_dir / f"{engagement.engagement_id}.json"
    data = engagement.to_dict()
    path.write_text(json.dumps(data, indent=2), encoding="utf-8")

    latest = base / "latest_engagement.json"
    latest.write_text(json.dumps(data, indent=2), encoding="utf-8")
    return path


def load_engagement(engagement_id: str, base: Path = Path("outputs")) -> StrategicEngagement:
    """Load a persisted engagement by ID."""
    path = base / "engagements" / f"{engagement_id}.json"
    data = json.loads(path.read_text(encoding="utf-8"))
    return StrategicEngagement.model_validate(data)


def link_research_object(
    engagement: StrategicEngagement,
    research_id: str,
    *,
    base: Path = Path("outputs"),
) -> StrategicEngagement:
    """Append a Research Object ID to the engagement and re-persist."""
    ids = list(engagement.research_object_ids)
    if research_id not in ids:
        ids.append(research_id)
    updated = engagement.model_copy(update={"research_object_ids": ids})
    write_engagement(updated, base=base)
    return updated


def link_decision_model(
    engagement: StrategicEngagement,
    decision_model_id: str,
    *,
    base: Path = Path("outputs"),
) -> StrategicEngagement:
    """Set the decision_model_id on the engagement and re-persist (J7.0b)."""
    updated = engagement.model_copy(update={"decision_model_id": decision_model_id})
    write_engagement(updated, base=base)
    return updated
